-- liquibase formatted sql
-- changeset Ren:2
-- tables for sprint 5
-- Sponsor
CREATE TABLE sponsors (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                          first_name VARCHAR(20),
                          last_name VARCHAR(20),
                          image VARCHAR(1000),
                          image_name VARCHAR(100),
                          amount_kudos BIGINT,
                          PRIMARY KEY (id)
);
CREATE TABLE kudos (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                       sponsor_id BIGINT REFERENCES sponsors,
                       proof_skill_id BIGINT REFERENCES proofs_skills,
                       amount BIGINT,
                       PRIMARY KEY (id)
);