-- User
CREATE TABLE user_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    talent_id BIGINT,
    sponsor_id BIGINT,
    login VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    CONSTRAINT pk_user_info PRIMARY KEY (id)
);
CREATE TABLE authority (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    authority VARCHAR(20) NOT NULL,
    CONSTRAINT pk_authority PRIMARY KEY (id)
);
CREATE TABLE user_authorities (
    authority_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_user_authorities PRIMARY KEY (authority_id, user_id)
);
-- Foreign keys
ALTER TABLE talent_attached_file
ADD CONSTRAINT FK_TALENT_ATTACHED_FILE_ON_TALENT FOREIGN KEY (talent_id) REFERENCES talent (id);
ALTER TABLE talent_contact
ADD CONSTRAINT FK_TALENT_CONTACT_ON_TALENT FOREIGN KEY (talent_id) REFERENCES talent (id);
ALTER TABLE talent_description
ADD CONSTRAINT FK_TALENT_DESCRIPTION_ON_TALENT FOREIGN KEY (talent_id) REFERENCES talent (id);
ALTER TABLE talent_link
ADD CONSTRAINT FK_TALENT_LINK_ON_TALENT FOREIGN KEY (talent_id) REFERENCES talent (id);
ALTER TABLE talent_proofs
ADD CONSTRAINT FK_TALENT_PROOFS_ON_TALENT FOREIGN KEY (talent_id) REFERENCES talent (id);
ALTER TABLE user_info
ADD CONSTRAINT FK_USER_INFO_ON_TALENT FOREIGN KEY (talent_id) REFERENCES talent (id);
ALTER TABLE user_authorities
ADD CONSTRAINT FK_useaut_on_authority FOREIGN KEY (authority_id) REFERENCES authority (id);
ALTER TABLE user_authorities
ADD CONSTRAINT FK_useaut_on_user_info FOREIGN KEY (user_id) REFERENCES user_info (id);
ALTER TABLE kudos
ADD CONSTRAINT FK_KUDOS_ON_SPONSOR FOREIGN KEY (sponsor_id) REFERENCES sponsor (id);
ALTER TABLE kudos
ADD CONSTRAINT FK_KUDOS_ON_PROOF_SKILL FOREIGN KEY (proof_skill_id) REFERENCES proof_skill (id);
ALTER TABLE proof_skill
ADD CONSTRAINT FK_proof_skill_ON_TALENT_PROOF FOREIGN KEY (proof_id) REFERENCES talent_proofs (id);
ALTER TABLE proof_skill
ADD CONSTRAINT FK_proof_skill_ON_SKILL FOREIGN KEY (skill_id) REFERENCES skill (id);
ALTER TABLE talent_skill
ADD CONSTRAINT FK_talent_skill_ON_TALENT FOREIGN KEY (talent_id) REFERENCES talent (id);
ALTER TABLE talent_skill
ADD CONSTRAINT FK_talent_skill_ON_SKILL FOREIGN KEY (skill_id) REFERENCES skill (id);
-- Indexes
CREATE UNIQUE INDEX idx_login ON user_info (login)