-- liquibase formatted sql
-- changeset Ren:0
-- tables for sprint 5
-- Talent
CREATE TABLE talents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(20),
    last_name VARCHAR(20),
    specialization VARCHAR(30),
    image VARCHAR(1000),
    image_name VARCHAR(100),
    PRIMARY KEY (id)
);
CREATE TABLE attached_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    talent_id BIGINT NOT NULL REFERENCES talents,
    attached_file VARCHAR(100),
    PRIMARY KEY (id)
);
CREATE TABLE contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    talent_id BIGINT NOT NULL REFERENCES talents,
    contact VARCHAR(255),
    PRIMARY KEY (id)
);
CREATE TABLE descriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    talent_id BIGINT NOT NULL REFERENCES talents,
    bio VARCHAR(2000),
    addition_info VARCHAR(500),
    PRIMARY KEY (id)
);
CREATE TABLE links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    talent_id BIGINT NOT NULL REFERENCES talents,
    link VARCHAR(500),
    PRIMARY KEY (id)
);
CREATE TABLE proofs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    talent_id BIGINT NOT NULL REFERENCES talents,
    link VARCHAR(500),
    text VARCHAR(1000),
    status VARCHAR(20) NOT NULL,
    created TIMESTAMP,
    PRIMARY KEY (id)
);
CREATE TABLE skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    skill VARCHAR(50),
    PRIMARY KEY (id)
);
CREATE TABLE talents_skills (
    talent_id BIGINT NOT NULL REFERENCES talents,
    skill_id BIGINT NOT NULL REFERENCES skills,
    PRIMARY KEY (talent_id, skill_id)
);
CREATE TABLE proofs_skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    proof_id BIGINT NOT NULL REFERENCES proofs,
    skill_id BIGINT NOT NULL REFERENCES skills,
    PRIMARY KEY (id)
);
-- Створення складеного унікального індексу
CREATE UNIQUE INDEX ON proofs_skills (id, proof_id, skill_id);