name: Backend CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Test with Maven
        run: mvn -B clean test

  docker:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    needs: test

    steps:
      - name: Login to gitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
